sudo: required

lang: bash

services:
  - docker

before_install:
  - docker build -t lixinio/elasticsearch:6.2.4 .

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push lixinio/elasticsearch:6.2.4
